server:
  port: 35003

spring:
  application:
    name: trailer-service
  data:
    mongodb:
      uri: mongodb://localhost:38550/moviekeeper

axon:
  serializer:
    events: jackson
    messages: jackson
    general: xstream
