language: java
jdk:
  - openjdk11
jobs:
  - stage: Tests
    script: pushd movie-service && mvn test -B && popd
  -
    script: pushd trailer-service && mvn test -B && popd
  -
    script: pushd cast-service && mvn test -B && popd
  -
    script: pushd proxy-service && mvn test -B && popd