language: java
jdk:
  - openjdk11
jobs:
  include:
    - stage: Tests
      name: movie-service tests
      script: pushd movie-service && mvn test -B && popd
    -
      name: trailer-service tests
      script: pushd trailer-service && mvn test -B && popd
    -
      name: cast-service tests
      script: pushd cast-service && mvn test -B && popd
    -
      name: proxy-service tests
      script: pushd proxy-service && mvn test -B && popd
    -
      name: digital-release-tracker tests
      script: pushd digital-release-tracker && mvn test -B && popd