version: '3.7'

services:
  mongo:
    image: 'mongo:latest'
    command: mongod --port 38550
    ports:
      - '38550:38550'
    environment:
      MONGO_INITDB_DATABASE: moviekeeper
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  axon:
    image: 'axoniq/axonserver:4.2.4-jdk11'
    ports:
      - '8024:8024'
      - '8124:8124'
  api-gateway:
    image: 'nginx:latest'
    ports:
      - '35000:80'
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf:ro"
  movie-service:
    build:
      context: ./movie-service
    ports:
      - '35001:35001'
  cast-service:
    build:
      context: ./cast-service
    ports:
      - '35002:35002'
  trailer-service:
    build:
      context: ./trailer-service
    ports:
      - '35003:35003'
  proxy-service:
    build:
      context: ./proxy-service
    ports:
      - '35004:35004'
