version: '3.7'

services:
  gateway:
    container_name: api-gateway
    image: 'nginx:latest'
    network_mode: host
    ports:
      - '35000:80'
    volumes:
    - "$PWD/nginx.conf:/etc/nginx/nginx.conf:ro"