server:
  port: 35001

spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: mongodb://localhost:38550/moviekeeper
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://mongo:38550/moviekeeper
axon:
  axonserver:
    servers: axon