server:
  port: 35001

spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: mongodb://localhost:38550/moviekeeper

axon:
  serializer:
    events: jackson
    messages: jackson
    general: xstream
  distributed:
    enabled: true
