server:
  port: 35001

spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: mongodb://localhost:38550/moviekeeper
#axon:
#  eventhandling:
#    processors:
#      name:
#        mode: tracking